
name: Staging environment deployment

on:
    push:
        branches: ["main"]
        paths:
          - "src/main/java/**"
          - "src/main/resources/**"
          - "pom.xml"
          - "Dockerfile"
    

jobs:

    
    Build-image:
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: continue3010/blog-service:release-${{ github.sha }}
        
    Update-manifest:
        runs-on: ubuntu-latest
        needs: Build-image
        if: ${{ success() }}
        steps:
            -
                name: Checkout infrastructure repo
                uses: actions/checkout@v3
                with:
                    repository: DevOpsOrganization2025/infrastructures
                    ref: 'main'
                    token: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Update blog service manifest
                run: |
                    git config --global user.email "dinhquangdaklak2003@gmail.com"
                    git config --global user.name "Continue3010"
                    sed -i 's#continue3010/blog-service:[^[:space:]]*#continue3010/blog-service:release-${{ github.sha }}#g' ./production/blog-service/blog-deploy.yaml
                    git add ./production/blog-service/blog-deploy.yaml
                    git commit -m "Update blog-service version to release-${{ github.sha }} in production environment"
                    git push origin main
